sonata_user:
    security_acl: true
    manager_type: orm # can be orm or mongodb
    admin:
        user:
            class:      Application\Sonata\UserBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle